### ISSUE TITLE
REP46: "Veterinary Active Surveillance Report" counts # of animals sampled versus # of samples.

### ISSUE THREAD

**Issue by NatalieShapiro** [EIDSS/EIDSS7#444]
**Summary**
When generating the 2022 Veterinary Active Surveillance Report, the "sampled #" lists the # of animals sampled versus the actual number of samples. For example, we explored the number of anthrax samples in the report. It says "28." However, when we looked into the aggregate information, it was 28 buffalo tested with a total of 24 tests. The number should reflect 24 based on the definition of # sampled. I confirmed this issue in the room. 

**Details**
Environment: (GAT or External): External
Script ID (or enter ad hoc if ad hoc): REP46 (validating data portion)
Username: NFAVetEpi or AdjaraRegionalVet
Severity (optional):

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to Reports > Vet Reports > Vet Active Surveillance and generate the report 
2. Record the "# sampled for anthrax" (28)
3. Go into vet surveillance sessions and search for "anthrax." Go through all of the records. The third is the only record with aggregate information (28 animals sampled, 24 samples).
4. Confirm with Anatoly about the definition of "# sampled" on the report (should reflect 24)

**Expected behavior**
I expected the number for anthrax to say "24" on the vet active surveillances report. 

**Screenshots**

![Veterinary Active Survelliance Report - Sampled #](https://user-images.githubusercontent.com/105503558/182687106-f8943fdd-fb74-47f3-9de4-00678d266952.PNG)

**Additional context**

**Comment by mwe4** [comment]
Updated stored proc to return # Samples for Sampled #

Report.USP_REP_VET_ActiveSurveillance

This will be reflected in the next deploy.

**Comment by karlasomera** [comment]
Unable to close this ticket due to:  
1.  Report ran but it states that there was 1 chicken sample but two were annotated in Session ID VASTBTBZ2200xk under surveillance session.  In addition it stated that there were 2137 planned but I was only able to locate 1,489 in the Surveillance Campaign.  In addition, I generated an archive report where the Brucelosis-Canis for Cow/Bull should reflect a total of 6 samples vs. 1 in the report.  The same issue occurred in the influenza-Avian - Goose the report shows 1 sample and the session ID VASTBTBZ2200WJ shows 7 samples.  I will send the reports to Jaya to show where I captured the information that i was verifying as stated on the script.  At this time I do not recommend closing out this bug.

**Comment by karlasomera** [comment]
Unable to close this GitHub ticket.  Report not matching the numbers that are identified on the report to the Vet Surveillance session and Surveillance Campaign

The brucellosis - Canis - ID VASTBTBZ2200WI show that there were s6 total samples with 1 animal.  The report shows o planned and 1 sampled.  

I can set time to go over this Script with the team as needed tomorrow to show the reports and Surveillance Sessions.

**Comment by karlasomera** [comment]
Completed the updated script as recommended by Peraton Team.  No additional concerns.  Recommend to close out this bug.
