### ISSUE TITLE
Script Discrepancies throughout the print scripts 

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#47]
**Summary**

The script labels, data elements, and steps to conduct testing have many discrepancies which results in invalid testing.  

**To Reproduce**
1. Log in as ANY user and review the following scripts: AMD 04, 05, 06, 07, 09, 10

**Expected behavior**
Scripts should align to the system and what is required to complete proper testing. 

Screenshots**
Review the print scripts

**Issue severity**
For testing this is Major for the system itself minor. 

**Build**
79

**Comment by christhompson17** [comment]
This issue needs to be cross-walked back to the requirements and use cases to determine if the script has the correct labels, or if the application has the correct labels. If the script is correct, and the application is incorrect, then this is a valid bug. Otherwise, this can be closed as a script error.
