### ISSUE TITLE
human>person ID PER23001265470 age mistake 123 years old 

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#521]
**Summary**
human>person ID PER23001265470 age mistake 123 years old 

**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional):  function
Username: bakuradze
Build: 
Severity (optional): Critical

**To Reproduce** 
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… person ID PER23001265470 see the age
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/128576431/231450533-692ee6b6-6021-4f73-9002-42e715a95f7b.png)

**Additional context**

**Comment by jkkannan** [comment]
Identified two issues on walk-through:
No warning message if user attempts to enter a person with age greater than 100 years. Expected behavior: System would display a warning message.
System allows entry of person with age of greater than 200 years. Expected behavior: System would not allow and display error message.

**Comment by bakuradzebakuradze** [comment]
When we register a person over 100 years old the system displays a warning message.
The issue is resolved
