### ISSUE TITLE
Tests grid

### ISSUE THREAD

**Issue by srbatni** [EIDSS/EIDSS7#72]
**Summary**
HUM190024 had two duplicate records listed in both tests in the tests tab; one should have been negative for Tularemia, the other should have been positive for measles.

**To Reproduce**
1. Log in as: Russell Peters 
2. Go to: Human Disease Report 
3. Click on: Tests tab 

**Expected behavior**
The two records in the test tab should have been different; one should have been negative for Tularemia, the other should've been positive for measles.

**Screenshots**

![image](https://user-images.githubusercontent.com/52708365/60911502-2d191e80-a238-11e9-94e6-9f2448500a4d.png)

**Additional details:**
 - Build: v7 80.0
 - Script title (enter ad hoc if not script-based):HPS04

**Issue severity**
Severity (critical, major, minor, low): Minor

**Additional context**

**Comment by EBH2001** [comment]
This issue is not reproducible.  It was mainly a test data issue.

Was able to fix issue and complete the script.  Some additional issues were noticed and those were logged separately.

**PLEASE SEE ATTACHMENT**

[HPS04_GitHub#72_Connected_human_disease_report_SomeIssues.docx](https://github.com/EIDSS/EIDSS7/files/3399697/HPS04_GitHub.72_Connected_human_disease_report_SomeIssues.docx)
