### ISSUE TITLE
In the window - "Details about the contact" in the area - "Current address" the inscription "Foreign address" is visible, which is incorrect (only "address" should be written), and below it the fields of the region and district are marked with * as mandatory fields, which I think are not is required (see image below).

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#797]
**Summary**
In the window - "Details about the contact" in the area - "Current address" the inscription "Foreign address" is visible, which is incorrect (only "address" should be written), and below it the fields of the region and district are marked with * as mandatory fields, which I think are not is required (see image below).
**Details**
Country: Georgia
Scenario ID (or enter ad hoc if ad hoc):
If ad hoc, Category (Function, customization, , migration, integration) (optional): 
Username: maka tsilsoani
Build: 
Severity (MANDATORY): minor

**To Reproduce**
Steps to reproduce the behavior (if in scripted testing, can refer to script step):
1. Go to… 
2. Click on… 

**Expected behavior**

**Screenshots**
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/e87e607d-ebd6-48d4-ab6d-18ac6a9fde0b)

**Additional context**

**Comment by herashchenkoa** [comment]
The behavior of the form is as expected. In the Current Address section for the selected person, it is possible to see 2 addresses Current OR Foreign. The 'Foreign Address' field by default should be unchecked. If the 'Foreign Address' check-box is checked, then fields of the Current address will be hidden. AND (Foreign Address) Country (Foreign Address) Address fields will appear instead. Please verify to confirm that the issue was resolved.

**Comment by bakuradzebakuradze** [comment]
The issue is not resolved

**Comment by bakuradzebakuradze** [comment]
fields of the region and district are marked with * as mandatory fields which should not be a mandatory field

**Comment by bakuradzebakuradze** [comment]
The issue remains open

**Comment by bakuradzebakuradze** [comment]
The issue is closed
