### ISSUE TITLE
ADM15 - Manage Disease Group

### ISSUE THREAD

**Issue by Aj-Kakar** [EIDSS/EIDSS7#85]
**Summary**
When adding a new disease group the system doesn't  return a confirmation message of the submission and doesn't save the submission.

**To Reproduce**
1. Log in as parkermason
2. Go to Disease Group Disease 
3. Click on +
4. Fill in the disease information and hit submit

**Expected behavior**
system should confirm disease group submission and save the submission

**Screenshots**
None

**Additional details:**
 - Build: 81
 - Script title: ADM15 - Manage Disease Group

**Issue severity**
Major

**Comment by christhompson17** [comment]
Confirmed in GAT. Disease group submission closes and does not save returning back to the "Disease Group - Disease Matrix". No error provided.

**Comment by EBH2001** [comment]
This issue is not reproducible in Build 83.1.  Was able to save all diseases and they display in matrix table successfully

**PLEASE SEE ATTACHMENT
[ADM15_GitHub#85_Add_Disease_Group_NotReproducible.docx](https://github.com/EIDSS/EIDSS7/files/3389853/ADM15_GitHub.85_Add_Disease_Group_NotReproducible.docx)
**

**Comment by jkkannan** [comment]
Closed during GAT remediation.  Able to successfully save and retrieve record.
