### ISSUE TITLE
Data of field “Date of Final case classification” is not migrated from v6 to v7

### ISSUE THREAD

**Issue by bakuradzebakuradze** [EIDSS/EIDSS7#858]
### Country

Georgia

### Username

bakuradze

### Build number

7.0.402

### Language

None

### Severity (MANDATORY)

1 - Critical

### Module

Human

### Description of the steps to reproduce

Step: HDR>Final Outcome>Date of Final Case Classification
![image](https://github.com/EIDSS/EIDSS7/assets/128576431/2af58c4d-e352-468e-821d-6d1b5ceb0b98)

**Comment by bakuradzebakuradze** [comment]
HWEB0019B2X0

**Comment by herashchenkoa** [comment]
In EIDSSv6.1 there are 2 fields: 'Date of Final Case Classification' and 'Final Diagnosis Date'.
1. Based on GG Customization, 'Date of Final Case Classification' field is hidden. So no data is entered in this field in EIDSSv6.1.  
2. But, the field 'Final Diagnosis Date' is in use in EIDSSv6.1. It calculates based on the following rule:  If <Changed Diagnosis (if known)> from Notification tab is not blank, then equals to <Date of changed diagnosis>, otherwise equals to <Diagnosis Date> from Notification tab. 
3. As in EIDSSv7, there are no 'Changed Diagnosis'/'Date of Changed Diagnosis' fields in EIDSSv7, field 'Final Diagnosis Date' was not implemented (instead Connected Disease Report feature was introduced). 
4. The logic of the Human Disease Report and Connected Disease Report will be reviewed during CCB in March 2024.

**Comment by TulendinovT** [comment]
In EIDSSv6.1 there are 2 fields: 'Date of Final Case Classification' and 'Final Diagnosis Date'.
1. Based on GG Customization, 'Date of Final Case Classification' field is hidden. So no data is entered in this field in EIDSSv6.1. The issue described in the bug is inaccurate, as GG users do not enter data in the field 'Date of Final Case Classification; as it is hidden. 
2. But, the field 'Final Diagnosis Date' is in use in EIDSSv6.1. It calculates based on the following rule:  If <Changed Diagnosis (if known)> from Notification tab is not blank, then equals to <Date of changed diagnosis>, otherwise equals to <Diagnosis Date> from Notification tab. 
3. As in EIDSSv7, there are no Changed Diagnosis/Date fields in EIDSSv7, field 'Final Diagnosis Date' was not implemented (instead Connected Disease Report is introduced). 
4. The logic of the Human Disease Report and Connected Disease Report will be reviewed during CCB in March 2024.

**Comment by TulendinovT** [comment]
Changed Diagnosis and Date of Changed Diagnosis is implemented in v7. Could you please check it by previous comment with rules for calculation of Final Diagnosis Date?

**Comment by bakuradzebakuradze** [comment]
It is also not downloaded for example of the age of one patient, I am sending you pictures
![ნელი 7 ასაკი](https://github.com/user-attachments/assets/c74b3b6c-a5e4-4ec1-8088-d1e830264fad)
![ნელი 6 ასაკი](https://github.com/user-attachments/assets/2b759739-5042-40dc-b1f6-a68ac271de50)
The date of final case classification box has also disappeared
![არა არის ნელი](https://github.com/user-attachments/assets/8616624a-f7ed-4c80-a11f-12aff10a1de0)

**Comment by bakuradzebakuradze** [comment]
The issue remains open
